### PR TITLE
Add new versions of loopback scripts

### PR DESCRIPTION
**Pull request by abjugard**
Bardatorn uses PulseAudio, recent versions of PulseAudio have modules that handle loopback. This is better because the system gives the PulseAudio started processes higher CPU priority than regular user started processes, improving latency.

### CODE REVIEW

**Comment by oherik** [comment]
If this could solve the latency issue we've been having with the karaoke mics, that would be pretty great.

**Comment by oherik** [comment]
Can this be closed, seeing that the loopback scripts have been recently updated?

**Comment by Dr-Horv** [comment]
@abjugard ?

**Comment by abjugard** [comment]
Yes, this can be closed, was fixed by commit 66c5506

**Pull request closed without merging**
